version: "2"
services:
  ackee:
    image: ghcr.io/janw/ackee
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ackee
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db

    ports:
      - "27017:27017"