const REFERRERS_TYPE_WITH_SOURCE = 'WITH_SOURCE'
const REFERRERS_TYPE_NO_SOURCE = 'NO_SOURCE'
const REFERRERS_TYPE_ONLY_SOURCE = 'ONLY_SOURCE'

export default {
	REFERRERS_TYPE_WITH_SOURCE,
	REFERRERS_TYPE_NO_SOURCE,
	REFERRERS_TYPE_ONLY_SOURCE,
}