name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: 'Build and test'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: yarn test

      - run: yarn coveralls

      - name: Parallel Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  coveralls:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Finished Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          parallel-finished: true
